### ISSUE TITLE
运行 README 示例程序有错

### ISSUE THREAD

**Issue by bingohuang** [qlang-libs/qlang#2]
首先，编译不通过，因为最新版的qlang，qlang.New 原型改变：

```
ql, err := qlang.New(options)
```

改为：

```
ql := qlang.New()
```

我已提了相应的PR： #1 
其次，编译通过，但运行不通过，报错如下：

```
panic: /Users/bingo/.gvm/pkgsets/go1.6.2/global/src/github.com/qlang-libs/types/slice.ql:1: runtime error: "expectations/main.ql": no such file or directory


goroutine 1 [running]:
panic(0x376700, 0xc820341670)
    /Users/bingo/.gvm/gos/go1.6.2/src/runtime/panic.go:481 +0x3e6
log.Panicln(0xc82010fea8, 0x1, 0x1)
    /Users/bingo/.gvm/gos/go1.6.2/src/log/log.go:334 +0xc1
main.main()
    /Users/bingo/IdeaProjects/qlang-study/play/play.go:33 +0x415
exit status 2
```

请问该如何修正？

**Comment by Focinfi** [comment]
错误提示没有 "expectations/main.ql" 这个文件，原因是没有引入 expectations 包。

添加 expectations 即可：

``` shell
cd $QLANG_PATH
git clone https://github.com/qlang-libs/expectations
```

**Comment by bingohuang** [comment]
是的，我后来也意识到是这个问题，然后开始找qlang-libs下的包，发现有了仓库是叫`expections`，但不是`expectations`，少了一个`a`，是否是作者笔误了？

**Comment by Focinfi** [comment]
确实是拼写错误，已将 expecttions 改成 expectations，多谢提醒
